### ISSUE TITLE
Modifying the animate-in and out duration

### ISSUE THREAD

**Issue by steveoh** [jamiebuilds/tailwindcss-animate#55]
https://github.com/jamiebuilds/tailwindcss-animate/blob/ac0dd3a3c81681b78f1d8ea5e7478044213995e1/index.js#L16

The generated code is

```css
.data-\[state\=open\]\:animate-in[data-state=open] {
  animation-name: enter;
  animation-duration: 150ms;
  --tw-enter-opacity: initial;
  --tw-enter-scale: initial;
  --tw-enter-rotate: initial;
  --tw-enter-translate-x: initial;
  --tw-enter-translate-y: initial;
}
```

applying a duration-1000 to the same node is ignored.

the node css

```
transition-[width,_height] duration-1000 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out data-[state=open]:fade-in data-[state=closed]:zoom-out data-[state=open]:zoom-in
```

Do I need to modify the theme? Is there a different class to use?
